Milestone 3: Awesome books - with ES6
white3d/Awesome-books---with-ES6 pull request #1
Opened 2022-03-22 07:35 UTC by white3d

In this milestone, I did the following:

    - Added the entry point for JavaScript code called index.js
    - Added index.css file for styles.
    - Added the main index.html file and linked index.js and index.css files there.
    - Added a directory called modules.
    - Re-created Awesome book app using ES6.
    - Displayed current date using Luxon.

2022-03-22 16:46 UTC, ShoiraTa requested changes
STATUS: CHANGES REQUIRED 🟡 
----
Hi @white3d ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)


 ## Required Changes  :recycle: 

- [ ] Please kindly update the README file by adding all the relevant sections as `getting started`, `Authors`, `License` etc. Please add the project description as well. 

- [ ] Check the comments under the review.

## Optional suggestions

- [ ] OPTIONAL: After I click on refresh button, it takes too long for page to get refreshed. I suggest to take a look at this issue 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 16:46 UTC, ShoiraTa commented on .gitignore
> +node_modules/
- [ ] Please make sure to delete the node_modules from the repository. Here is what you can do:
- Delete node modules, 
- Push changes 
- Run `npm install `

2022-03-22 16:46 UTC, ShoiraTa commented on modules/deleteBookRecord.js
> +/* eslint-disable import/prefer-default-export */
- [ ] Please avoid making custom changes in disabling `eslint`.
If you have one function to export, then at the end of document you can write 

`export default myFunction`
then import it:
`import myFunction from './modules/index.js'`

2022-03-22 16:46 UTC, ShoiraTa commented on modules/displayTime.js
> +/* eslint-disable import/prefer-default-export */
- [ ] Please avoid making custom changes in disabling `eslint`.
If you have one function to export, then at the end of document you can write 

`export default myFunction`
then import it:
`import myFunction from './modules/index.js'`

2022-03-22 16:46 UTC, ShoiraTa commented on modules/recordNewBook.js
> +/* eslint-disable import/prefer-default-export */
- [ ] Please avoid making custom changes in disabling `eslint`.
If you have one function to export, then at the end of document you can write 

`export default myFunction`
then import it:
`import myFunction from './modules/index.js'`

2022-03-22 16:46 UTC, ShoiraTa commented on modules/deleteBookRecord.js
> +};
- [ ] It is not possible to delete books, after page refresh all books are listed back. Please try to delete books and check your console:
<img width="476" alt="Screenshot 2022-03-22 at 20 41 12" src="https://user-images.githubusercontent.com/77038610/159530733-cef2ec9f-0bda-4f47-a4cf-e7835f5a4cf5.png">

- [ ] Please make sure to address this issue 🙏🏻

2022-03-23 17:39 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Edward, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-31 12:00 UTC, merged